# DeepSeek Harness One-Click Launcher - Installer
# ------------------------------------------------
# Detects node.exe, dsh install dir, Chrome path, and the DeepSeek Harness PWA
# app-id, then generates DeepSeekHarnessLauncher.vbs with the detected values
# and creates a desktop shortcut "DeepSeek Harness.lnk".
#
# Usage:  powershell -ExecutionPolicy Bypass -File .\install.ps1
#         pwsh -File .\install.ps1

$ErrorActionPreference = "Stop"

Write-Host "=== DeepSeek Harness One-Click Launcher Installer ===" -ForegroundColor Cyan

# ---------- 1. locate node.exe ----------
$node = $null
try { $node = (Get-Command node.exe -ErrorAction Stop).Source } catch {}
if (-not $node -or -not (Test-Path $node)) {
    # common fallbacks
    foreach ($candidate in @(
        "$env:ProgramFiles\nodejs\node.exe",
        "${env:ProgramFiles(x86)}\nodejs\node.exe",
        "$env:LOCALAPPDATA\Programs\nodejs\node.exe"
    )) {
        if (Test-Path $candidate) { $node = $candidate; break }
    }
}
if (-not $node) { Write-Host "ERROR: node.exe not found. Install Node.js first." -ForegroundColor Red; exit 1 }
Write-Host "node.exe:  $node" -ForegroundColor Green

# ---------- 2. locate dsh bin.js ----------
$dshBin = $null
$npmPrefix = $null
try { $npmPrefix = (npm prefix -g 2>$null).Trim() } catch {}
if ($npmPrefix) {
    $candidate = Join-Path $npmPrefix "node_modules\@deepseek-ai\dsh\lib\bin.js"
    if (Test-Path $candidate) { $dshBin = $candidate }
}
if (-not $dshBin) {
    # search the global node_modules
    foreach ($base in @($npmPrefix, "$env:APPDATA\npm", "$env:USERPROFILE\AppData\Roaming\npm")) {
        if (-not $base) { continue }
        $candidate = Join-Path $base "node_modules\@deepseek-ai\dsh\lib\bin.js"
        if (Test-Path $candidate) { $dshBin = $candidate; $npmPrefix = $base; break }
    }
}
if (-not $dshBin) { Write-Host "ERROR: @deepseek-ai/dsh not found. Install it first (npm i -g @deepseek-ai/dsh)." -ForegroundColor Red; exit 1 }
Write-Host "dsh bin.js: $dshBin" -ForegroundColor Green

# ---------- 3. locate Chrome ----------
$chrome = $null
$chromeKeys = @(
    "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe",
    "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe",
    "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe"
)
foreach ($key in $chromeKeys) {
    try {
        $val = (Get-ItemProperty $key -ErrorAction Stop).'(default)'
        if ($val -and (Test-Path $val)) { $chrome = $val; break }
    } catch {}
}
if (-not $chrome) {
    foreach ($candidate in @(
        "$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
        "${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe",
        "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe"
    )) { if (Test-Path $candidate) { $chrome = $candidate; break } }
}
if (-not $chrome) { Write-Host "WARNING: Chrome not found; PWA window won't open. Install Chrome first." -ForegroundColor Yellow }
$chromeProxy = $chrome -replace "chrome\.exe$", "chrome_proxy.exe"
Write-Host "Chrome:     $chrome" -ForegroundColor Green

# ---------- 4. detect DeepSeek Harness PWA app-id ----------
$appId = ""
$webApps = Join-Path $env:LOCALAPPDATA "Google\Chrome\User Data\Default\Web Applications"
if (Test-Path $webApps) {
    $appDirs = Get-ChildItem $webApps -Directory -Filter "_crx_*" -ErrorAction SilentlyContinue
    foreach ($dir in $appDirs) {
        $lnk = Get-ChildItem $dir.FullName -Filter "*.lnk" -ErrorAction SilentlyContinue | Select-Object -First 1
        if (-not $lnk) { continue }
        $wsh = New-Object -ComObject WScript.Shell
        $s = $wsh.CreateShortcut($lnk.FullName)
        $name = [System.IO.Path]::GetFileNameWithoutExtension($lnk.Name)
        if ($name -like "*DeepSeek*" -or $s.Description -like "*DeepSeek*") {
            if ($s.Arguments -match "--app-id=(\S+)") {
                $appId = $Matches[1]
                Write-Host "PWA app-id: $appId (window title: $name)" -ForegroundColor Green
                break
            }
        }
    }
}
if (-not $appId) {
    Write-Host "NOTE: DeepSeek Harness PWA not found in Chrome. The launcher will open a plain app window via --app URL fallback." -ForegroundColor Yellow
}

# ---------- 5. generate the VBS ----------
$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
$vbsPath = Join-Path $scriptDir "DeepSeekHarnessLauncher.vbs"

$vbs = @"
' DeepSeek Harness One-Click Launcher (auto-generated by install.ps1)
' Starts dsh web (hidden) if needed, then opens the PWA standalone window.

Option Explicit

Dim shell, fso, i, portUp, ready
Set shell = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")

Const PORT = 3080
Const DSH_DIR = "$npmPrefix"
Const NODE = "$node"
Const BIN = "$dshBin"
Const CHROME = "$chromeProxy"
Const APP_ID = "$appId"
Const URL = "http://127.0.0.1:3080"

Dim SCRIPT_DIR
SCRIPT_DIR = fso.GetParentFolderName(WScript.ScriptFullName)
Const LOGFILE = SCRIPT_DIR & "\launcher.log"
Const TMPFILE = SCRIPT_DIR & "\portcheck.txt"

Function PortListening()
    Dim e, ln, up
    up = False
    shell.Run "cmd /c netstat -ano | findstr :3080 > """ & TMPFILE & """ 2>nul", 0, True
    If fso.FileExists(TMPFILE) Then
        Set e = fso.OpenTextFile(TMPFILE, 1, False, 0)
        Do While Not e.AtEndOfStream
            ln = e.ReadLine()
            If InStr(ln, "LISTENING") > 0 Then
                up = True
                Exit Do
            End If
        Loop
        e.Close
    End If
    PortListening = up
End Function

portUp = PortListening()

If Not portUp Then
    shell.CurrentDirectory = DSH_DIR
    shell.Run """" & NODE & """ """ & BIN & """ --profile web", 0, False

    ready = False
    For i = 1 To 90
        WScript.Sleep 1000
        If PortListening() Then
            ready = True
            Exit For
        End If
    Next
    If Not ready Then
        MsgBox "DeepSeek Harness server failed to start within 90 seconds." & vbCrLf & _
               "Manual: cd " & DSH_DIR & " && dsh web", vbExclamation, "DeepSeek Harness"
    End If
End If

If APP_ID <> "" Then
    shell.Run """" & CHROME & """ --profile-directory=Default --app-id=" & APP_ID, 1, False
Else
    shell.Run """" & CHROME & """ --app=" & URL, 1, False
End If
"@

[System.IO.File]::WriteAllText($vbsPath, $vbs, [System.Text.Encoding]::Unicode)
Write-Host "VBS generated: $vbsPath" -ForegroundColor Green

# ---------- 6. create desktop shortcut ----------
$desktop = [Environment]::GetFolderPath("Desktop")
$lnkPath = Join-Path $desktop "DeepSeek Harness.lnk"
$wsh = New-Object -ComObject WScript.Shell
$sc = $wsh.CreateShortcut($lnkPath)
$sc.TargetPath = "wscript.exe"
$sc.Arguments = "`"$vbsPath`""
$sc.Description = "DeepSeek Harness - one-click launch"
# try to use the PWA icon if available
$icon = $null
if ($appId) {
    $iconDir = Join-Path $webApps "_crx_$appId"
    $ico = Get-ChildItem $iconDir -Filter "*.ico" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($ico) { $icon = $ico.FullName }
}
if ($icon) { $sc.IconLocation = "$icon,0" }
$sc.Save()
Write-Host "Shortcut created: $lnkPath" -ForegroundColor Green

Write-Host ""
Write-Host "=== Done! Double-click the desktop 'DeepSeek Harness' shortcut to launch. ===" -ForegroundColor Cyan
